import { FC, ReactNode } from "react";
import Head from "next/head";
import Link from "next/link";

type Props = {
  title: string,
  children: ReactNode
}

export const Layout: FC<Props> = ({ children, title = 'T3 Stack' }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app"></meta>
        <Link rel="icon" href="/favicon.ico"></Link>
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {children}
      </main>
    </>
  )
}